# Generated by Django 4.2.16 on 2025-03-14 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.ImageField(default='default.jpg', upload_to='images/'),
        ),
    ]
